/*A- Básicas*/
/*1*/
SELECT TITULO, AUTOR
FROM LIBROS
WHERE TIPO = 'no' AND PRECIO_ORI > 21;
/*2*/
SELECT NRO_LIBRO, PRECIO_ORI, EDICION
FROM LIBROS
WHERE (TIPO = 'no' OR PRECIO_ORI > 21) AND EDICION > 1985;
/*3*/
SELECT AUTOR, EDICION 
FROM LIBROS 
WHERE AUTOR LIKE 'L%';
/*4*/
SELECT AUTOR,EDICION 
FROM LIBROS 
WHERE AUTOR NOT LIKE 'G%';
/*5*/
SELECT AUTOR, PRECIO_ORI, EDICION
FROM LIBROS 
WHERE AUTOR LIKE '%RR%';
/*6*/
SELECT TITULO, EDICION
FROM LIBROS
WHERE PRECIO_ORI < 12 OR PRECIO_ORI > 25;
/*7*/
SELECT DISTINCT TIPO, EDICION
FROM LIBROS
ORDER BY EDICION ASC;
/*8*/
SELECT NRO_LIBRO, EDICION, TIPO, PRECIO_ORI, PRECIO_ACT, (PRECIO_ACT - PRECIO_ORI) AS 'DIFERENCIA'
FROM LIBROS
ORDER BY TIPO ASC, DIFERENCIA ASC;
/*9*/
SELECT NRO_LIBRO,EDICION,TIPO,PRECIO_ORI,PRECIO_ACT,(PRECIO_ACT - PRECIO_ORI) AS 'DIFERENCIA'
FROM LIBROS
WHERE TIPO = 'es';
/*10*/
SELECT NRO_LIBRO, PRECIO_ORI, EDICION
FROM LIBROS
WHERE (EDICION > 1985) AND (TIPO = 'no' OR PRECIO_ORI > 21);
/*11*/
SELECT TITULO, AUTOR
FROM LIBROS
WHERE TIPO = 'no' OR PRECIO_ORI > 21;
/*12*/
SELECT TITULO, PRECIO_ORI
FROM LIBROS
WHERE EDICION IN(1948,1978,1985);
/*13*/
SELECT TITULO, EDICION
FROM LIBROS
WHERE PRECIO_ORI BETWEEN 12 AND 25;
/*14*/
SELECT TITULO, PRECIO_ORI, EDICION
FROM LIBROS
WHERE TITULO LIKE '%R%S%';
/*15*/
SELECT TITULO, PRECIO_ORI, EDICION
FROM LIBROS
WHERE SUBSTRING(TITULO, 2, 1) = 'A';
/*16*/
SELECT TITULO, EDICION
FROM LIBROS
WHERE TIPO = 'no'
ORDER BY EDICION ASC;
/*17*/
SELECT NRO_LIBRO, EDICION, TIPO
FROM LIBROS
WHERE PRECIO_ORI > 20
ORDER BY EDICION DESC, NRO_LIBRO ASC;
/*18*/
SELECT NRO_LIBRO, EDICION, PRECIO_ORI, PRECIO_ACT, (PRECIO_ACT - PRECIO_ORI) AS 'DIFERENCIA'
FROM LIBROS
WHERE (PRECIO_ACT - PRECIO_ORI) > 10;
/*19*/
SELECT NRO_LIBRO, EDICION, TIPO, PRECIO_ORI, PRECIO_ACT, (PRECIO_ACT - PRECIO_ORI) AS 'DIFERENCIA'
FROM LIBROS
WHERE (PRECIO_ACT - PRECIO_ORI) > 10
ORDER BY DIFERENCIA DESC;





/*B - Funciones de Agregación, Having*/
/*1*/
SELECT
SUM(PRECIO_ORI) AS 'SUMA_PRECIO_ORI',
AVG(PRECIO_ORI) AS 'PROMEDIO_PRECIO_ORI',
MIN(PRECIO_ACT) AS 'PRECIO_ACT_MIN',
MAX(PRECIO_ACT) AS 'PRECIO_ACT_MAX'
FROM LIBROS
WHERE EDICION > 1970;
/*2*/
SELECT
SUM(PRECIO_ORI + PRECIO_ACT) AS 'SUMA_TOTAL',
AVG(PRECIO_ORI + PRECIO_ACT) AS 'PROMEDIO_TOTAL',
MIN(PRECIO_ACT - PRECIO_ORI) AS 'DIFERENCIA_MIN',
MAX(PRECIO_ACT - PRECIO_ORI) AS 'DIFERENCIA_MAX'
FROM LIBROS
WHERE EDICION > 1970;
/*3*/
SELECT
COUNT(*) AS 'CANTIDAD_LIBROS',
TIPO,
MIN(PRECIO_ORI) AS 'PRECIO_ORI_MIN',
MAX(PRECIO_ORI) AS 'PRECIO_ORI_MAX'
FROM LIBROS
WHERE PRECIO_ORI > 45
GROUP BY TIPO;
/*4*/
SELECT
TIPO, 
SUM(PRECIO_ORI) AS 'TOTAL_PRECIO_ORI',
AVG(PRECIO_ACT) AS 'PROMEDIO_PRECIO_ACT'
FROM LIBROS
WHERE EDICION<> 1946
GROUP BY TIPO 
HAVING SUM(PRECIO_ORI) > 40;
/*5*/
SELECT
TIPO,
AVG(PRECIO_ORI) AS 'PROMEDIO_PRECIO_ORI'
FROM LIBROS
GROUP BY TIPO
HAVING AVG(PRECIO_ORI) > (SELECT AVG(PRECIO_ORI) FROM LIBROS);
/*6*/
SELECT
TIPO,
SUM(PRECIO_ORI) AS 'TOTAL_PRECIO_ORI',
AVG(PRECIO_ACT) AS 'PROMEDIO_PRECIO_ACT'
FROM LIBROS
WHERE EDICION BETWEEN 1946 AND 1975
GROUP BY TIPO;
/*7*/
SELECT
TIPO,
SUM(PRECIO_ORI) AS 'TOTAL_PRECIO_ORI',
AVG(PRECIO_ACT) AS 'PROMEDIO_PRECIO_ACT'
FROM LIBROS
WHERE EDICION<> 1946
GROUP BY TIPO
ORDER BY PROMEDIO_PRECIO_ACT ASC;
/*8*/
SELECT
TIPO,
SUM(PRECIO_ORI) AS 'TOTAL_PRECIO_ORI',
AVG(PRECIO_ACT) AS 'PROMEDIO_PRECIO_ACT'
FROM LIBROS
WHERE EDICION BETWEEN 1946 AND 1975
GROUP BY TIPO;
/*9*/
SELECT 
TRABAJO,
MAX(SALARIO) AS 'SALARIO_MAXIMO'
FROM LECTORES
GROUP BY TRABAJO;
/*10*/
SELECT
TRABAJO,
AVG(SALARIO) AS 'SALARIO_PROMEDIO'
FROM LECTORES
WHERE DIRECCION LIKE '% - Capital'
GROUP BY TRABAJO;


/*C - Uso de Operadores Especiales (ALL, ANY) , SubQuerys*/
/*1*/
SELECT SUBSTRING(NOMBRE,1,5) AS 'PRIMEROS_CINCO_CARACT_NOMBRE'
FROM LECTORES;
/*2*/
SELECT 
NOMBRE,
DIRECCION
FROM LECTORES
WHERE NRO_LECTOR IN(SELECT NRO_LECTOR FROM PRESTAMOS);
/*3*/
SELECT
NRO_LIBRO,
TITULO,
PRECIO_ACT
FROM LIBROS
WHERE PRECIO_ORI = (SELECT MAX(PRECIO_ORI) FROM LIBROS);
/*4*/
SELECT
NRO_LIBRO,
TITULO,
PRECIO_ORI
FROM LIBROS
WHERE PRECIO_ORI > (SELECT AVG(PRECIO_ACT) FROM LIBROS);
/*5*/
SELECT
NRO_LIBRO,
TITULO,
PRECIO_ORI
FROM LIBROS
WHERE PRECIO_ORI > ALL(SELECT PRECIO_ORI FROM LIBROS WHERE TIPO = 'no');
/*6*/
SELECT
NRO_LIBRO,
TITULO,
PRECIO_ORI
FROM LIBROS
WHERE PRECIO_ORI > ANY (SELECT PRECIO_ORI FROM LIBROS WHERE TIPO = 'no');

/*D - Consultas en varias tablas – uso de join (inner join – left join – right join)*/
/*1*/
SELECT
L.TITULO,
P.F_PREST,
P.F_DEVOL
FROM PRESTAMOS P
INNER JOIN LIBROS L ON P.NRO_LIBRO = L.NRO_LIBRO;
/*2*/
SELECT
L.NRO_LIBRO,
L.TITULO,
P.F_PREST,
P.F_DEVOL
FROM PRESTAMOS P
INNER JOIN LIBROS L ON P.NRO_LIBRO = L.NRO_LIBRO;
/*3*/
SELECT L.NRO_LECTOR, L.NOMBRE, COUNT(P.NRO_LECTOR) AS CANTIDAD_PRESTAMOS
FROM LECTORES L
LEFT JOIN PRESTAMOS P ON L.NRO_LECTOR = P.NRO_LECTOR
GROUP BY L.NRO_LECTOR, L.NOMBRE;
/*4*/
SELECT C.NRO_LIBRO, L.TITULO, C.NRO_COPIA, COUNT(P.NRO_COPIA) AS CANTIDAD_PRESTAMOS
FROM COPIAS C
INNER JOIN LIBROS L ON C.NRO_LIBRO = L.NRO_LIBRO
LEFT JOIN PRESTAMOS P ON C.NRO_LIBRO = P.NRO_LIBRO AND C.NRO_COPIA = P.NRO_COPIA
GROUP BY C.NRO_LIBRO, L.TITULO, C.NRO_COPIA;
/*5*/
SELECT L.NRO_LIBRO, L.TITULO, COUNT(P.NRO_LIBRO) AS CANTIDAD_PRESTAMOS
FROM LIBROS L
LEFT JOIN PRESTAMOS P ON L.NRO_LIBRO = P.NRO_LIBRO
WHERE YEAR(P.F_PREST) >= 2012
GROUP BY L.NRO_LIBRO, L.TITULO;
/*6*/
SELECT C.NRO_LIBRO, L.TITULO, C.NRO_COPIA, COUNT(P.NRO_COPIA) AS CANTIDAD_PRESTAMOS
FROM COPIAS C
INNER JOIN LIBROS L ON C.NRO_LIBRO = L.NRO_LIBRO
LEFT JOIN PRESTAMOS P ON C.NRO_LIBRO = P.NRO_LIBRO AND C.NRO_COPIA = P.NRO_COPIA
GROUP BY C.NRO_LIBRO, L.TITULO, C.NRO_COPIA
HAVING COUNT(P.NRO_COPIA) > 1;
/*7*/
SELECT 
L.NRO_LIBRO,
L.TITULO,
C.NRO_COPIA,
P.F_PREST
FROM LIBROS L
LEFT JOIN PRESTAMOS P ON L.NRO_LIBRO = P.NRO_LIBRO 
LEFT JOIN COPIAS C ON L.NRO_LIBRO = C.NRO_LIBRO AND C.NRO_COPIA = P.NRO_COPIA;
/*8*/
SELECT
LE.NRO_LECTOR,
LE.NOMBRE,
L.NRO_LIBRO,
L.TITULO,
L.TIPO,
P.F_PREST
FROM LECTORES LE
LEFT JOIN PRESTAMOS P ON LE.NRO_LECTOR = P.NRO_LECTOR
LEFT JOIN LIBROS L ON P.NRO_LIBRO = L.NRO_LIBRO
WHERE P.F_DEVOL IS NOT NULL AND (L.TIPO = 'no' OR L.TIPO= 'cu');
/*9*/
SELECT 
L.TITULO,
LE.NOMBRE
FROM PRESTAMOS P
LEFT JOIN LIBROS L ON P.NRO_LIBRO = L.NRO_LIBRO
LEFT JOIN LECTORES LE ON P.NRO_LECTOR = LE.NRO_LECTOR;
/*10*/
SELECT
LE.NRO_LECTOR,
LE.NOMBRE,
P.F_PREST
FROM  LECTORES LE 
LEFT JOIN PRESTAMOS P ON LE.NRO_LECTOR = P.NRO_LECTOR
WHERE  P.F_PREST IS NOT NULL AND P.F_DEVOL IS NULL;
/*11*/
SELECT 
LE.NRO_LECTOR,
LE.NOMBRE,
L.NRO_LIBRO,
L.TITULO,
P.F_PREST
FROM LECTORES LE
LEFT JOIN PRESTAMOS P ON LE.NRO_LECTOR = P.NRO_LECTOR
LEFT JOIN LIBROS L ON P.NRO_LIBRO = L.NRO_LIBRO
WHERE P.F_DEVOL IS NOT NULL;
/*12*/
SELECT 
LE.NRO_LECTOR,
LE.NOMBRE,
L.NRO_LIBRO,
L.TITULO,
P.F_PREST
FROM LECTORES LE
LEFT JOIN PRESTAMOS P ON LE.NRO_LECTOR = P.NRO_LECTOR
LEFT JOIN LIBROS L ON P.NRO_LIBRO = L.NRO_LIBRO
WHERE P.F_DEVOL IS NOT NULL AND (L.TIPO = 'no' OR L.TIPO = 'cu');
/*13*/
SELECT 
LE.NRO_LECTOR,
LE.NOMBRE,
P.F_PREST
FROM LECTORES LE
LEFT JOIN PRESTAMOS P ON LE.NRO_LECTOR = P.NRO_LECTOR



/*E – Insert – Update - Delete*/
/*1*/
INSERT INTO LIBROS (NRO_LIBRO, TITULO, AUTOR, TIPO, PRECIO_ORI, PRECIO_ACT, EDICION, ESTADO)
VALUES (5078914,'LAS MIL Y UNA NOCHES 2','GALLAND A. 2','no',25.30,37.20,1948, Null)
INSERT INTO COPIAS (NRO_LIBRO, NRO_COPIA, ESTADO)
VALUES (5078914, 1, Null),
       (5078914, 2, Null),
       (5078914, 3, Null),
       (5078914, 4, Null),
       (5078914, 5, Null);
/*2*/
UPDATE LIBROS
SET PRECIO_ACT = 35.35
WHERE TITULO = 'LAS MIL Y UNA NOCHES';


                                          /*3 DUDAS*/
SELECT COUNT(*) AS AntesDeEliminacion
FROM LECTORES;


DELETE FROM LECTORES
WHERE SALARIO < 1000;
DELETE FROM COPIAS
WHERE NRO_LIBRO = 1;



SELECT COUNT(*) AS DespuesDeEliminacion
FROM LECTORES;





 /*F – PLUS*/
/*1*/
SELECT *
FROM COPIAS
INNER JOIN LECTORES ON (1=1)
INNER JOIN LIBROS ON (1=1)
INNER JOIN PRESTAMOS ON (1=1)
INNER JOIN TIPOLIBROS ON (1=1);


